/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Profissional;
import Classes.Serviço;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADM
 */
public class CadastrarServiço extends javax.swing.JInternalFrame {

    public Profissional getProfissao() {
        return profissao;
    }

    public void setProfissao(Profissional profissao) {
        this.profissao = profissao;
    }

    public Principal getPrincipal() {
        return principal;
    }

    public void setPrincipal(Principal principal) {
        this.principal = principal;
    }

    Profissional profissao;
    Principal principal;
     ArrayList<Serviço> servicos;

    /**
     * Creates new form CadastrarServiço
     */
    public CadastrarServiço() {
        servicos= new ArrayList();
        initComponents();
        
        DefaultTableModel modelo= (DefaultTableModel) jTableCadastrarServico.getModel();
        jTableCadastrarServico.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastrarServico = new javax.swing.JTable();

        setClosable(true);
        setTitle("Cadastrar Serviço");
        setToolTipText("");

        jLabel1.setText("Descrição:");

        jLabel2.setText("Preço:");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonAtualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonAtualizar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTableCadastrarServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCadastrarServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastrarServicoMouseClicked(evt);
            }
        });
        jTableCadastrarServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCadastrarServicoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastrarServico);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        String descricao= jTextFieldDescricao.getText();
        double preco= Double.parseDouble(jTextFieldPreco.getText());
        Serviço servico = new Serviço(descricao,preco);
        servicos.add(servico);
        JOptionPane.showMessageDialog(this, "Serviço cadastrado");
        
        DefaultTableModel dtmServico = (DefaultTableModel)jTableCadastrarServico.getModel();
        Object[] dados={jTextFieldDescricao.getText(), jTextFieldPreco.getText()};
        dtmServico.addRow(dados);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if(jTableCadastrarServico.getSelectedRow()!= -1){
        DefaultTableModel dtmServico = (DefaultTableModel) jTableCadastrarServico.getModel();
        dtmServico.removeRow(jTableCadastrarServico.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableCadastrarServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastrarServicoMouseClicked
       if(jTableCadastrarServico.getSelectedRow()!= -1){
            jTextFieldDescricao.setText(jTableCadastrarServico.getValueAt(jTableCadastrarServico.getSelectedRow(), 0).toString());
            jTextFieldPreco.setText(jTableCadastrarServico.getValueAt(jTableCadastrarServico.getSelectedRow(), 1).toString());
        }else{
            JOptionPane.showMessageDialog(this, "selecione uma linha para atualizar");
        }
    }//GEN-LAST:event_jTableCadastrarServicoMouseClicked

    private void jTableCadastrarServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCadastrarServicoKeyReleased
       if(jTableCadastrarServico.getSelectedRow()!= -1){
            jTextFieldDescricao.setText(jTableCadastrarServico.getValueAt(jTableCadastrarServico.getSelectedRow(), 0).toString());
            jTextFieldPreco.setText(jTableCadastrarServico.getValueAt(jTableCadastrarServico.getSelectedRow(), 1).toString());
        }else{
            JOptionPane.showMessageDialog(this, "selecione uma linha para atualizar");
        }
    }//GEN-LAST:event_jTableCadastrarServicoKeyReleased

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
       if(jTableCadastrarServico.getSelectedRow()!= -1){
            jTableCadastrarServico.setValueAt(jTextFieldDescricao.getText(), jTableCadastrarServico.getSelectedRow(), 0);
            jTableCadastrarServico.setValueAt(jTextFieldPreco.getText(), jTableCadastrarServico.getSelectedRow(), 1);
        }else{
            JOptionPane.showMessageDialog(this, "selecione uma linha para atualizar");
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastrarServico;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldPreco;
    // End of variables declaration//GEN-END:variables
}
