/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Profissional;


/**
 *
 * @author ADM
 */
public class Principal extends javax.swing.JFrame {

    Profissional profissao;

    public Profissional getProfissao() {
        return profissao;
    }

    public void setProfissao(Profissional profissao) {
        this.profissao = profissao;
    }

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemProfissional = new javax.swing.JMenuItem();
        jMenuItemServiço = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuPagamento = new javax.swing.JMenu();
        jMenuItemEfetuarPagamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Salão de beleza");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        jMenuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_form_add.png"))); // NOI18N
        jMenuCadastrar.setText("Cadastrar");

        jMenuItemProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jMenuItemProfissional.setText("Profissional");
        jMenuItemProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfissionalActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemProfissional);

        jMenuItemServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jMenuItemServiço.setText("Serviço");
        jMenuItemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiçoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemServiço);

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCliente);

        jMenuBar1.add(jMenuCadastrar);

        jMenuPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jMenuPagamento.setText("Pagamento");

        jMenuItemEfetuarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_add.png"))); // NOI18N
        jMenuItemEfetuarPagamento.setText("Efetuar pagamento");
        jMenuItemEfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEfetuarPagamentoActionPerformed(evt);
            }
        });
        jMenuPagamento.add(jMenuItemEfetuarPagamento);

        jMenuBar1.add(jMenuPagamento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfissionalActionPerformed
        CadastrarProfissional cp = new CadastrarProfissional();
        jDesktopPane1.add(cp);
        cp.setProfissao(getProfissao());
        cp.setPrincipal(this);
        cp.setVisible(true);

    }//GEN-LAST:event_jMenuItemProfissionalActionPerformed

    private void jMenuItemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiçoActionPerformed
       CadastrarServiço cs = new CadastrarServiço();
       jDesktopPane1.add(cs);
       cs.setProfissao(getProfissao());
       cs.setPrincipal(this);
       cs.setVisible(true);
    }//GEN-LAST:event_jMenuItemServiçoActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
       CadastrarCliente cc = new CadastrarCliente();
       jDesktopPane1.add(cc);
       cc.setProfissao(getProfissao());
       cc.setPrincipal(this);
       cc.setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemEfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEfetuarPagamentoActionPerformed
       EfetuarPagamento ep = new EfetuarPagamento();
       jDesktopPane1.add(ep);
       ep.setProfissao(getProfissao());
       ep.setPrincipal(this);
       ep.setVisible(true);
    }//GEN-LAST:event_jMenuItemEfetuarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEfetuarPagamento;
    private javax.swing.JMenuItem jMenuItemProfissional;
    private javax.swing.JMenuItem jMenuItemServiço;
    private javax.swing.JMenu jMenuPagamento;
    // End of variables declaration//GEN-END:variables
}
